version: "3.5"

services:
  bullboard:
    container_name: bullboard
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: host
      REDIS_PORT: 6379
      REDIS_USERNAME: username
      REDIS_PASSWORD: password
      REDIS_USE_TLS: 'true'
